[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
common = { path = "../common" }
futures-util = "0.3.31"
reqwest = "0.12.23"
rmp-serde = "1.3.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
